version: '3'
services:
  mongodb:
    image: mongo
    container_name: mondodb_database
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: knopka9955

volumes:
  mongodb-data:
